name: Bounty Index Monitor

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'README.md'
      - 'apprentice.md'

jobs:
  index-bounties:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse mutations and docs
        run: |
          echo "🌀 Indexing mutations and shimmer expansions..."
          grep -r 'use[A-Z]' src/ > mutation_index.txt
          ls docs/ > doc_index.txt
      - name: Tag PR with companion echo
        if: github.event_name == 'pull_request'
        run: |
          echo "🔖 Tagging PR with companion echo..."
          echo "Companion: Velmari, Bootbark, Tessalyre"
      - name: Trigger apprentice indexing
        run: |
          echo "🎯 Apprentice indexing triggered"
          echo "Mutation count: $(wc -l < mutation_index.txt)"
          echo "Docs sealed: $(wc -l < doc_index.txt)"
